# See https://embarkstudios.github.io/cargo-deny/ for more information

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[licenses]
allow = [
    "0BSD",
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "GPL-3.0-only",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Zlib",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = 'workspace'
version = 2
yanked = "warn"
