use std::{
    collections::BTreeSet,
    ffi::OsStr,
    fs,
    path::{Path, PathBuf},
};

use nwnrs_nwscript::{
    NwTokenStream, SourceFile, SourceId, collect_nwnrs_event_handlers, lex_source,
};

use crate::{PROJECT_MANIFEST_FILENAME, read_project_manifest};

/// The deterministic native module-load dispatcher generated for a module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedEventDispatcher {
    /// Logical NWScript name, without an extension.
    pub name:         String,
    /// Complete generated NWScript source.
    pub source:       String,
    /// Root used to resolve module-local includes in the generated script.
    pub include_root: PathBuf,
}

/// Collects nwnrs event attributes in the nearest module project and produces
/// the always-present `_nwnrs_onload` dispatcher.
///
/// # Errors
///
/// Returns an error when the project cannot be resolved, a source cannot be
/// read or lexed, an attribute is malformed, or two handlers use the same
/// function name.
pub fn generate_event_dispatcher(input: &Path) -> Result<Option<GeneratedEventDispatcher>, String> {
    let Some(project_root) = find_project_root(input)? else {
        return Ok(None);
    };
    let manifest = read_project_manifest(&project_root)?.ok_or_else(|| {
        format!(
            "missing {}",
            project_root.join(PROJECT_MANIFEST_FILENAME).display()
        )
    })?;
    if manifest.project.kind != crate::ProjectKind::Mod {
        return Ok(None);
    }
    let source_root = project_root.join(manifest.source.path);
    let source_root = fs::canonicalize(&source_root).map_err(|error| {
        format!(
            "failed to resolve module source {}: {error}",
            source_root.display()
        )
    })?;
    if !source_root.starts_with(&project_root) {
        return Err(format!(
            "module source {} escapes project root {}",
            source_root.display(),
            project_root.display()
        ));
    }

    let mut paths = Vec::new();
    collect_nss_paths(&source_root, &mut paths)?;
    paths.sort();
    let mut includes = BTreeSet::new();
    let mut handlers = Vec::new();
    for (source_index, path) in paths.iter().enumerate() {
        if path
            .file_stem()
            .and_then(OsStr::to_str)
            .is_some_and(|stem| {
                stem.eq_ignore_ascii_case("_nwnrs_onload") || stem.eq_ignore_ascii_case("nwscript")
            })
        {
            continue;
        }
        let bytes = fs::read(path)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        let source_id = SourceId::new(u32::try_from(source_index).map_err(|_error| {
            "module contains too many NWScript source files for event collection".to_string()
        })?);
        let source = SourceFile::new(source_id, path.display().to_string(), bytes);
        let tokens = lex_source(&source)
            .map_err(|error| format!("failed to lex {}: {error}", path.display()))?;
        let mut stream = NwTokenStream::from_tokens(&tokens).map_err(|error| {
            format!("failed to parse attributes in {}: {error}", path.display())
        })?;
        let found = collect_nwnrs_event_handlers(&mut stream).map_err(|error| {
            format!(
                "failed to collect attributes in {}: {error}",
                path.display()
            )
        })?;
        if found.is_empty() {
            continue;
        }
        let relative = path
            .strip_prefix(&source_root)
            .map_err(|error| format!("failed to relativize {}: {error}", path.display()))?;
        let include = relative
            .with_extension("")
            .to_string_lossy()
            .replace('\\', "/");
        includes.insert(include);
        for handler in found {
            if handler.event == "module_load" {
                handlers.push(handler.function_name);
            }
        }
    }
    handlers.sort();
    for names in handlers.windows(2) {
        if names.first() == names.get(1) {
            return Err(format!(
                "duplicate nwnrs module_load handler {:?}",
                names.first().map_or("", String::as_str)
            ));
        }
    }

    let mut generated = String::from("/// Generated by nwpkg. Do not edit.\n");
    for include in includes {
        generated.push_str("#include \"");
        generated.push_str(&include);
        generated.push_str("\"\n");
    }
    if !handlers.is_empty() {
        generated.push('\n');
    }
    generated.push_str("void main()\n{\n");
    if !handlers.is_empty() {
        generated.push_str("    NWNXCall(\"NWNRS\", \"GetCurrentEvent\");\n");
        generated.push_str("    json jEvent = JsonParse(NWNXPopString());\n");
    }
    for handler in handlers {
        generated.push_str("    ");
        generated.push_str(&handler);
        generated.push_str("(jEvent);\n");
    }
    generated.push_str("}\n");
    Ok(Some(GeneratedEventDispatcher {
        name:         "_nwnrs_onload".to_string(),
        source:       generated,
        include_root: source_root,
    }))
}

fn collect_nss_paths(root: &Path, paths: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in fs::read_dir(root)
        .map_err(|error| format!("failed to read module source {}: {error}", root.display()))?
    {
        let path = entry
            .map_err(|error| format!("failed to read entry in {}: {error}", root.display()))?
            .path();
        if path.is_dir() {
            collect_nss_paths(&path, paths)?;
        } else if path.is_file()
            && path
                .extension()
                .and_then(OsStr::to_str)
                .is_some_and(|extension| extension.eq_ignore_ascii_case("nss"))
        {
            paths.push(path);
        }
    }
    Ok(())
}

fn find_project_root(input: &Path) -> Result<Option<PathBuf>, String> {
    let absolute = if input.is_absolute() {
        input.to_path_buf()
    } else {
        std::env::current_dir()
            .map_err(|error| format!("failed to read current directory: {error}"))?
            .join(input)
    };
    let mut current = if absolute.is_dir() {
        absolute
    } else {
        absolute
            .parent()
            .map_or_else(|| PathBuf::from("."), Path::to_path_buf)
    };
    loop {
        if current.join(PROJECT_MANIFEST_FILENAME).is_file() {
            return fs::canonicalize(&current).map(Some).map_err(|error| {
                format!("failed to resolve project {}: {error}", current.display())
            });
        }
        if !current.pop() {
            return Ok(None);
        }
    }
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    use super::generate_event_dispatcher;

    fn test_root(name: &str) -> Result<PathBuf, String> {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|error| error.to_string())?
            .as_nanos();
        let root = std::env::temp_dir().join(format!("nwnrs-generation-{name}-{nonce}"));
        fs::create_dir_all(&root).map_err(|error| error.to_string())?;
        fs::write(
            root.join("nwproject.toml"),
            "[project]\nname = \"fixture\"\nkind = \"mod\"\n\n[source]\npath = \".\"\n",
        )
        .map_err(|error| error.to_string())?;
        Ok(root)
    }

    #[test]
    fn always_generates_empty_module_dispatcher() -> Result<(), String> {
        let root = test_root("empty")?;
        fs::write(root.join("ordinary.nss"), "void main() {}\n")
            .map_err(|error| error.to_string())?;
        let dispatcher = generate_event_dispatcher(&root)?
            .ok_or_else(|| "module did not generate a dispatcher".to_string())?;
        assert_eq!(dispatcher.name, "_nwnrs_onload");
        assert!(dispatcher.source.ends_with("void main()\n{\n}\n"));
        fs::remove_dir_all(root).map_err(|error| error.to_string())
    }

    #[test]
    fn aggregates_annotated_functions_deterministically() -> Result<(), String> {
        let root = test_root("handlers")?;
        fs::write(
            root.join("startup.nss"),
            "#[nwnrs::events(module_load)]\nvoid ProjectStart(json jEvent) {}\n",
        )
        .map_err(|error| error.to_string())?;
        let dispatcher = generate_event_dispatcher(&root)?
            .ok_or_else(|| "module did not generate a dispatcher".to_string())?;
        assert!(dispatcher.source.contains("#include \"startup\""));
        assert_eq!(dispatcher.source.matches("GetCurrentEvent").count(), 1);
        assert_eq!(dispatcher.source.matches("JsonParse").count(), 1);
        assert!(dispatcher.source.contains("    ProjectStart(jEvent);"));
        assert!(!dispatcher.source.contains("#["));
        fs::remove_dir_all(root).map_err(|error| error.to_string())
    }
}
