name: Label
on:
    pull_request:
        branches: [ main ]
env:
    CARGO_TERM_COLOR: always
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.head.repo.full_name
        || github.repository }}-${{ github.head_ref || github.ref_name }}
    cancel-in-progress: true
jobs:
    label:
        name: Label PR
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v6.0.2
            - name: Apply labels
              uses: actions/labeler@v6.1.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/labeler.yml
