name: Release

on:
    push:
        branches:
            - main

env:
    CARGO_TERM_COLOR: always

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: read
            id-token: write
        steps:
            - uses: actions/checkout@v6.0.2
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - uses: ./.github/actions/setup-rust

            - name: Run release-plz
              uses: release-plz/action@v0.5
              with:
                  command: release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release-pr:
        name: Release PR
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
            pull-requests: write
        concurrency:
            group: release-plz-${{ github.ref }}
            cancel-in-progress: false
        steps:
            - uses: actions/checkout@v6.0.2
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - uses: ./.github/actions/setup-rust
            - name: Close old release PR
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # List all opened PRs which head branch starts with "release-plz-"
                  release_pr=$(gh pr list --state='open' --json number,headRefName --jq '.[] | select(.headRefName | startswith("release-plz-")) | .number')
                  # Close the release PR if there is one
                  if [[ -n "$release_pr" ]]; then
                      echo "Closing old release PR $release_pr"
                      gh pr close $release_pr
                  else
                      echo "No open release PR"
                  fi
            - name: Run release-plz
              uses: release-plz/action@v0.5
              with:
                  command: release-pr
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
